import logging


logging.basicConfig(filename='mylog.txt', encoding='utf-8')
logging.error('エラーが発生しました')
# ERROR:root:エラーが発生しました
